import {
  User,
  ToolsetDefinition,
  SandboxExecuteRequest,
  SandboxExecuteResponse,
} from '@refly/openapi-schema';
import { ToolParams } from '@langchain/core/tools';
import { RunnableConfig } from '@langchain/core/runnables';
import { z } from 'zod/v3';
import { AgentBaseTool, AgentBaseToolset, AgentToolConstructor, ToolCallResult } from '../base';

export interface ReflyService {
  execute: (user: User, req: SandboxExecuteRequest) => Promise<SandboxExecuteResponse>;
}

export interface SandboxParams extends ToolParams {
  user: User;
  reflyService: ReflyService;
}

export const SandboxToolsetDefinition: ToolsetDefinition = {
  key: 'sandbox',
  // TODO: Change to https://www.scalebox.dev/ when it is ready
  domain: 'https://www.cloudsway.ai/',
  labelDict: {
    en: 'Sandbox',
    'zh-CN': '沙盒工具',
  },
  descriptionDict: {
    en: 'Create an isolated environment to execute specific tasks securely, preventing security risks and privacy leaks',
    'zh-CN': '创建隔离环境以安全地执行特定任务，避免安全风险和隐私泄露',
  },
  tools: [
    {
      name: 'execute',
      descriptionDict: {
        en: 'Execute a specific code snippet in an isolated sandbox environment',
        'zh-CN': '在隔离的沙盒环境中执行特定的代码片段',
      },
    },
  ],
};

export class Execute extends AgentBaseTool<SandboxParams> {
  name = 'execute';
  toolsetKey = SandboxToolsetDefinition.key;

  schema = z.object({
    code: z.string().describe('The code to execute'),
    language: z
      .enum(['python', 'javascript', 'typescript', 'r', 'java', 'bash', 'node', 'nodejs', 'deno'])
      .describe('Programming language for code execution'),
    timeout: z.number().optional().default(30).describe('Execution timeout in seconds'),
  });

  description = `
Execute code in a secure sandbox environment with isolated file systems.

** File System Structure **
Two mount points are available in the sandbox:
- /mnt/refly/drive (read-only): User uploaded files from drive
- /mnt/refly/workflow (read-write): Workflow shared workspace for intermediate files

** File Access Patterns **

Read user files from drive (read-only):
\`\`\`python
import pandas as pd
# Read user uploaded file
df = pd.read_csv('/mnt/refly/drive/data.csv')
\`\`\`

Write workflow files (read-write):
\`\`\`python
# Write intermediate result
df.to_csv('/mnt/refly/workflow/result.csv', index=False)

# Generate charts
import matplotlib.pyplot as plt
fig.savefig('/mnt/refly/workflow/chart.png')
\`\`\`

Read outputs from previous workflow nodes:
\`\`\`python
# Read file generated by previous node
previous_result = pd.read_csv('/mnt/refly/workflow/previous_output.csv')
\`\`\`

** Best Practices **
- /mnt/refly/drive contains user uploaded files (read-only)
- /mnt/refly/workflow is shared across all workflow nodes (read-write)
- Files written to /mnt/refly/workflow are available to subsequent nodes
- Each workflow execution has an isolated workspace
- Always include all necessary imports
- Filter warnings only once to avoid duplicates:
  \`\`\`python
  import warnings
  warnings.filterwarnings('once', category=UserWarning)
  \`\`\`

** Common Patterns **
\`\`\`python
# Read user files from drive
data = pd.read_csv('/mnt/refly/drive/sales.csv')
config = json.load(open('/mnt/refly/drive/config.json'))

# Process and write workflow files
processed.to_csv('/mnt/refly/workflow/processed.csv')
fig.savefig('/mnt/refly/workflow/chart.png')

# Read from previous workflow nodes
prev_data = pd.read_csv('/mnt/refly/workflow/step1_output.csv')
\`\`\`
`;

  protected params: SandboxParams;

  constructor(params: SandboxParams) {
    super(params);
    this.params = params;
  }

  async _call(
    input: z.infer<typeof this.schema>,
    _: any,
    config: RunnableConfig,
  ): Promise<ToolCallResult> {
    try {
      const { reflyService, user } = this.params;

      if (!reflyService) {
        return {
          status: 'error',
          error: 'Sandbox service is not available',
          summary: 'Sandbox service is not configured.',
        };
      }

      const version = config.configurable?.version;
      if (!version) {
        return {
          status: 'error',
          error: 'Version is required for sandbox execution',
          summary:
            'Version configuration is missing. Please ensure the execution context includes a version identifier.',
        };
      }

      const request: SandboxExecuteRequest = {
        code: input.code,
        language: input.language,
        timeout: input.timeout,
        version,
        parentResultId: config.configurable?.resultId,
        canvasId: config.configurable?.canvasId,
      };

      const result = await reflyService.execute(user, request);

      if (result.status === 'success') {
        const output = result.data?.output || 'No output';
        const executionTime = result.data?.executionTime || 0;
        const exitCode = result.data?.exitCode || 0;

        const summary = `**Result:**
📄 Output: ${output}
⏱️ Execution Time: ${executionTime}ms
✅ Exit Code: ${exitCode}`;

        return {
          status: 'success',
          data: {
            output,
            error: result.data?.error,
            exitCode,
            executionTime,
            parentResultId: config.configurable?.resultId,
            files: result.data?.files,
          },
          summary,
          creditCost: 1, // Placeholder credit cost
        };
      }

      // Handle error response
      let errorMessage = 'Code execution failed';

      if (result.errors && result.errors.length > 0) {
        errorMessage = result.errors.map((err) => `[${err.code}] ${err.message}`).join('; ');
      } else if (result.data?.error) {
        errorMessage = `Execution error: ${result.data.error}`;
      }

      return {
        status: 'error',
        error: errorMessage,
        summary: '❌ **Code execution failed**',
      };
    } catch (error) {
      const errorMsg =
        error instanceof Error ? error.message : 'Unknown error occurred while executing code';
      return {
        status: 'error',
        error: errorMsg,
        summary: '❌ **Unexpected error during code execution**',
      };
    }
  }
}

export class SandboxToolset extends AgentBaseToolset<SandboxParams> {
  toolsetKey = SandboxToolsetDefinition.key;
  tools = [Execute] satisfies readonly AgentToolConstructor<SandboxParams>[];
}
