name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    if: github.repository == 'refly-ai/refly'
    strategy:
      matrix:
        app: ['api', 'web']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for better caching

      - uses: pnpm/action-setup@v4
        if: matrix.app == 'web'
        with:
          run_install: false
          version: 8

      - name: Use Node.js
        uses: actions/setup-node@v4
        if: matrix.app == 'web'
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Get pnpm store directory
        if: matrix.app == 'web'
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        if: matrix.app == 'web'
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        if: matrix.app == 'web'
        run: pnpm install

      - name: Build
        run: pnpm build:web
        if: matrix.app == 'web'
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: reflyai
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker tags
        id: docker_tags
        run: |
          TAGS="reflyai/refly-${{ matrix.app }}:${{ github.sha }}"
          if [[ "${{ github.ref_name }}" == "main" || "${{ github.ref_name }}" == "stable" ]]; then
            TAGS="$TAGS,reflyai/refly-${{ matrix.app }}:nightly"
          fi
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/${{ matrix.app }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_tags.outputs.tags }}
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          cache-from: |
            type=registry,ref=reflyai/refly-${{ matrix.app }}:buildcache
            type=gha,scope=${{ github.workflow }}
          cache-to: |
            type=registry,ref=reflyai/refly-${{ matrix.app }}:buildcache,mode=max
            type=gha,scope=${{ github.workflow }},mode=max
